services:
  library-service-project:
    build:
      context: .
    container_name: library-service-project
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "
      python manage.py wait_for_db
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - telegram-bot

  telegram-bot:
    build:
      context: .
    container_name: telegram-bot
    env_file:
      - .env
    command: >
      sh -c "
      python telegram/telegram_bot.py"
    depends_on:
      - db

  db:
    image: postgres:16-alpine3.20
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:
