name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: library-service-project
          POSTGRES_USER: library-service-project
          POSTGRES_PASSWORD: library-service-project
        options: >-
          --health-cmd="pg_isready -U library-service-project" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    env:
      POSTGRES_DB: library-service-project
      POSTGRES_USER: library-service-project
      POSTGRES_PASSWORD: library-service-project
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        timeout-minutes: 5
        run: python manage.py test
